### ISSUE TITLE
Add reaction support for IRCcloud users.

### ISSUE THREAD

**Issue by soarn** [Chew/DIRCord#32]
👀

**Comment by Chew** [comment]
1) cinch doesn't support this. And it won't...ever.
2) Reactions are still in drafts on IRCv3, I really have no way of testing this.
3) The amount of servers that actually utilize reactions outside of irccloud servers, is 0.

We may revisit this issue in 3 years time, but until then, I'm not gonna let this clog up our issues.
Same goes for message editing/deleting, that's a whole different story.
