### ISSUE TITLE
Highlightable words as roles.

### ISSUE THREAD

**Issue by soarn** [Chew/DIRCord#35]
When you add a word to your highlighted list, it makes it a role on Discord, so then instead of mentioning you in the message, it mentions the role.
![59FB2EBB-7F8B-48DC-85DA-705CB7EFC114](https://user-images.githubusercontent.com/11000195/59862142-15d0ca80-9337-11e9-8dce-903165f0eaa3.jpeg)

**Comment by Chew** [comment]
This makes no sense, why would we need this??? It's just you on the server????
Plus, some setups don't enable the bot to make roles anyway. More setup and hassle for the end user.

**Comment by Chew** [comment]
Plus, it would need to add YOU to the role. Making it even more complicated.
